print("===========================================")
print("PERSONAL FINANCE CALCULATOR")
print("===========================================")
print("Inocome Details")
name = str(input('Enter your full name :'))
salary = float(input("salary:"))
annualbonus = float(input("annual bonus:"))
sideincome = float(input("Monthly side income:"))
print("Expense Details")
rent=float(input("Monthly Rent:"))
foodbudget=float(input("Monthly Food Budget:"))
transcost=float(input("Montly Transport cost:"))
utilities=float(input("Monthly Utilities:"))
Entertainment=float(input("Monthly Entertainment Budget:"))
print ("Saving Goal")
cursaving=float(input("Current Savings:"))
targetsaving=float(input("Target Saving:"))
desiredtime=float(input("desired time in months:"))
print("In how many months do you want to reach your goal? 12")
print ('calculating...')
print("===========================================")
print(name,"'s FINANCE CALCULATOR")
print("===========================================")
print("Inocome Details")
print (" income breakdown")
print("Salary",salary)
monthlybonus=annualbonus/12
print("Monthly Bonus:",monthlybonus)
print("side income:",sideincome)
c=salary+sideincome+monthlybonus
print("Total income:",c)
print("\n")
print("Expeneses:")
print("Rent:",rent)
print("Food",foodbudget)
print("Transport:",transcost)
print("Utilities:",utilities)
print("entertainment:",Entertainment)
b=rent+foodbudget+transcost+utilities+Entertainment
print("Total Expenses:",b)
print('\n')
print("Saving & Analysis:")
d=c-b
print("Monthly Savings:",d)
e=(d/c)*100
print("Saving Rate:",e)
g=(b/c)*100
print("Expense Ratio",g)
h=d*12
print("Annual Saving Potential: ",h)
print("\n")
print ("Saving goal planning:")
print("Current saving:",cursaving)
print("Traget saving:",targetsaving)
print("Savings gap:",targetsaving)
print("Desired Time :",desiredtime)
i=targetsaving/desiredtime
print("Needed Monthly Saving:",i)
j=targetsaving/d
print("You can reach in:",j,"months")
print("\n")
print("Weekly & Daily View:")
k=d/4
print("Weekly income:",k)
l=b/4
print("weekly expenses:",l)
m=k/7
print("Daily Income:",m)
n=l/7
print("Daily Expenses:",n)
print("\n")
print("Annual Overview:")
print("Annual Income",c*12)
print("Annual Expenses:",b*12)
print("Estimated Annual Savings:",d*12)
print("===========================================")
print("THANKS FOR USING THE CALCULATOR")
print("===========================================")
 